import { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import Image from 'next/image'

import Mint from '../components/Mint/mint'
import Head from 'next/head'
import { Button } from '@mui/material'
import { useRouter } from 'next/router'

const Adopt: NextPage = () => {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p className={styles.description}>this is mono</p>
        <Button
                  variant="contained"
                  color="primary"
                  onClick={() => {router.push('/adopt')}}
                >
                  Home
                </Button>
        <Mint />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Adopt
