import { Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import { Parallax, useParallax } from 'react-scroll-parallax'
import Mint from '../components/Mint/mint'
import styles from '../styles/Home.module.css'

const texts = [
  `Monsters are escaping the dungeons on a massive exodus never before seen. The kingdom has sent its brightest minds to investigate why this
  is happening.
  The sheer amount of escaping monster is just to much to fight off, without counting the offspring they are alying outside the dungeons.
  `,
]

const Home: NextPage = () => {
  return (
    <div className={styles.container} style={{
    }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <Grid
            container
            spacing={50}
            direction="column"
          >
            <Grid item>
              <div className={styles.title}>
               <Image src="/titlecryptomobs.png" width={2400} height={1350}/>
              </div>
              <Image src="/landingHeader.png" width={2400} height={1350}/>
              
            </Grid>
            <Grid item>
              <Parallax translateY={[-50,-125]} className={styles.transitionbottom}>
                <Image src="/caveTransitionbottom.png" width={2200} height={1350}/>
                <Parallax translateY={[-95,-120]} className={styles.transitiontop}>
                <div className={styles.transitiontext}>
                    {texts[0]}
                  </div>
                  <Image src="/caveTransitiontop.png" width={2200} height={1350}/>
                  
                </Parallax>
              </Parallax>
              
              <Image src="/landingDesigns.png" width={2400} height={1350}/>
            </Grid>
            <Grid item>
              <Parallax translateY={[-50,-115]} className={styles.transitionbottom}>
                <Image src="/caveTransitionbottom.png" width={2200} height={1350}/>
                <Parallax translateY={[-95,-120]} className={styles.transitiontop}>
                  <Image src="/caveTransitiontop.png" width={2200} height={1350}/>
                </Parallax>
              </Parallax>
              <Image src="/cavePreview.png" width={2400} height={1350}/>
            </Grid>
            <Grid item>
              <Parallax translateY={[-50,-118]} className={styles.transitionbottom}>
                <Image src="/caveTransitionbottom.png" width={2200} height={1350}/>
                <Parallax translateY={[-95,-118]} className={styles.transitiontop}>
                  <Image src="/caveTransitiontop.png" width={2200} height={1350}/>
                </Parallax>
              </Parallax>
              <div className={styles.cavetop}>
                <Image  src="/endtop.png" width={2400} height={1650}/>
              </div>
              <div className={styles.cavemiddletop}>
                <Image  src="/endmiddletop.png" width={2400} height={1650}/>
              </div>
              <div className={styles.cavemiddlebottom}>
                <Image  src="/endmiddlebottom.png" width={2400} height={1650}/>
              </div>
              
                <Image  src="/endbackcolor.png" width={2400} height={1650}/>
            </Grid>
          </Grid>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
